namespace HKX2
{
    public class hclObjectSpaceDeformerSixBlendEntryBlock : IHavokObject
    {
        public ushort m_boneIndices_0;
        public ushort m_boneIndices_1;
        public ushort m_boneIndices_10;
        public ushort m_boneIndices_11;
        public ushort m_boneIndices_12;
        public ushort m_boneIndices_13;
        public ushort m_boneIndices_14;
        public ushort m_boneIndices_15;
        public ushort m_boneIndices_16;
        public ushort m_boneIndices_17;
        public ushort m_boneIndices_18;
        public ushort m_boneIndices_19;
        public ushort m_boneIndices_2;
        public ushort m_boneIndices_20;
        public ushort m_boneIndices_21;
        public ushort m_boneIndices_22;
        public ushort m_boneIndices_23;
        public ushort m_boneIndices_24;
        public ushort m_boneIndices_25;
        public ushort m_boneIndices_26;
        public ushort m_boneIndices_27;
        public ushort m_boneIndices_28;
        public ushort m_boneIndices_29;
        public ushort m_boneIndices_3;
        public ushort m_boneIndices_30;
        public ushort m_boneIndices_31;
        public ushort m_boneIndices_32;
        public ushort m_boneIndices_33;
        public ushort m_boneIndices_34;
        public ushort m_boneIndices_35;
        public ushort m_boneIndices_36;
        public ushort m_boneIndices_37;
        public ushort m_boneIndices_38;
        public ushort m_boneIndices_39;
        public ushort m_boneIndices_4;
        public ushort m_boneIndices_40;
        public ushort m_boneIndices_41;
        public ushort m_boneIndices_42;
        public ushort m_boneIndices_43;
        public ushort m_boneIndices_44;
        public ushort m_boneIndices_45;
        public ushort m_boneIndices_46;
        public ushort m_boneIndices_47;
        public ushort m_boneIndices_48;
        public ushort m_boneIndices_49;
        public ushort m_boneIndices_5;
        public ushort m_boneIndices_50;
        public ushort m_boneIndices_51;
        public ushort m_boneIndices_52;
        public ushort m_boneIndices_53;
        public ushort m_boneIndices_54;
        public ushort m_boneIndices_55;
        public ushort m_boneIndices_56;
        public ushort m_boneIndices_57;
        public ushort m_boneIndices_58;
        public ushort m_boneIndices_59;
        public ushort m_boneIndices_6;
        public ushort m_boneIndices_60;
        public ushort m_boneIndices_61;
        public ushort m_boneIndices_62;
        public ushort m_boneIndices_63;
        public ushort m_boneIndices_64;
        public ushort m_boneIndices_65;
        public ushort m_boneIndices_66;
        public ushort m_boneIndices_67;
        public ushort m_boneIndices_68;
        public ushort m_boneIndices_69;
        public ushort m_boneIndices_7;
        public ushort m_boneIndices_70;
        public ushort m_boneIndices_71;
        public ushort m_boneIndices_72;
        public ushort m_boneIndices_73;
        public ushort m_boneIndices_74;
        public ushort m_boneIndices_75;
        public ushort m_boneIndices_76;
        public ushort m_boneIndices_77;
        public ushort m_boneIndices_78;
        public ushort m_boneIndices_79;
        public ushort m_boneIndices_8;
        public ushort m_boneIndices_80;
        public ushort m_boneIndices_81;
        public ushort m_boneIndices_82;
        public ushort m_boneIndices_83;
        public ushort m_boneIndices_84;
        public ushort m_boneIndices_85;
        public ushort m_boneIndices_86;
        public ushort m_boneIndices_87;
        public ushort m_boneIndices_88;
        public ushort m_boneIndices_89;
        public ushort m_boneIndices_9;
        public ushort m_boneIndices_90;
        public ushort m_boneIndices_91;
        public ushort m_boneIndices_92;
        public ushort m_boneIndices_93;
        public ushort m_boneIndices_94;
        public ushort m_boneIndices_95;
        public ushort m_boneWeights_0;
        public ushort m_boneWeights_1;
        public ushort m_boneWeights_10;
        public ushort m_boneWeights_11;
        public ushort m_boneWeights_12;
        public ushort m_boneWeights_13;
        public ushort m_boneWeights_14;
        public ushort m_boneWeights_15;
        public ushort m_boneWeights_16;
        public ushort m_boneWeights_17;
        public ushort m_boneWeights_18;
        public ushort m_boneWeights_19;
        public ushort m_boneWeights_2;
        public ushort m_boneWeights_20;
        public ushort m_boneWeights_21;
        public ushort m_boneWeights_22;
        public ushort m_boneWeights_23;
        public ushort m_boneWeights_24;
        public ushort m_boneWeights_25;
        public ushort m_boneWeights_26;
        public ushort m_boneWeights_27;
        public ushort m_boneWeights_28;
        public ushort m_boneWeights_29;
        public ushort m_boneWeights_3;
        public ushort m_boneWeights_30;
        public ushort m_boneWeights_31;
        public ushort m_boneWeights_32;
        public ushort m_boneWeights_33;
        public ushort m_boneWeights_34;
        public ushort m_boneWeights_35;
        public ushort m_boneWeights_36;
        public ushort m_boneWeights_37;
        public ushort m_boneWeights_38;
        public ushort m_boneWeights_39;
        public ushort m_boneWeights_4;
        public ushort m_boneWeights_40;
        public ushort m_boneWeights_41;
        public ushort m_boneWeights_42;
        public ushort m_boneWeights_43;
        public ushort m_boneWeights_44;
        public ushort m_boneWeights_45;
        public ushort m_boneWeights_46;
        public ushort m_boneWeights_47;
        public ushort m_boneWeights_48;
        public ushort m_boneWeights_49;
        public ushort m_boneWeights_5;
        public ushort m_boneWeights_50;
        public ushort m_boneWeights_51;
        public ushort m_boneWeights_52;
        public ushort m_boneWeights_53;
        public ushort m_boneWeights_54;
        public ushort m_boneWeights_55;
        public ushort m_boneWeights_56;
        public ushort m_boneWeights_57;
        public ushort m_boneWeights_58;
        public ushort m_boneWeights_59;
        public ushort m_boneWeights_6;
        public ushort m_boneWeights_60;
        public ushort m_boneWeights_61;
        public ushort m_boneWeights_62;
        public ushort m_boneWeights_63;
        public ushort m_boneWeights_64;
        public ushort m_boneWeights_65;
        public ushort m_boneWeights_66;
        public ushort m_boneWeights_67;
        public ushort m_boneWeights_68;
        public ushort m_boneWeights_69;
        public ushort m_boneWeights_7;
        public ushort m_boneWeights_70;
        public ushort m_boneWeights_71;
        public ushort m_boneWeights_72;
        public ushort m_boneWeights_73;
        public ushort m_boneWeights_74;
        public ushort m_boneWeights_75;
        public ushort m_boneWeights_76;
        public ushort m_boneWeights_77;
        public ushort m_boneWeights_78;
        public ushort m_boneWeights_79;
        public ushort m_boneWeights_8;
        public ushort m_boneWeights_80;
        public ushort m_boneWeights_81;
        public ushort m_boneWeights_82;
        public ushort m_boneWeights_83;
        public ushort m_boneWeights_84;
        public ushort m_boneWeights_85;
        public ushort m_boneWeights_86;
        public ushort m_boneWeights_87;
        public ushort m_boneWeights_88;
        public ushort m_boneWeights_89;
        public ushort m_boneWeights_9;
        public ushort m_boneWeights_90;
        public ushort m_boneWeights_91;
        public ushort m_boneWeights_92;
        public ushort m_boneWeights_93;
        public ushort m_boneWeights_94;
        public ushort m_boneWeights_95;

        public ushort m_vertexIndices_0;
        public ushort m_vertexIndices_1;
        public ushort m_vertexIndices_10;
        public ushort m_vertexIndices_11;
        public ushort m_vertexIndices_12;
        public ushort m_vertexIndices_13;
        public ushort m_vertexIndices_14;
        public ushort m_vertexIndices_15;
        public ushort m_vertexIndices_2;
        public ushort m_vertexIndices_3;
        public ushort m_vertexIndices_4;
        public ushort m_vertexIndices_5;
        public ushort m_vertexIndices_6;
        public ushort m_vertexIndices_7;
        public ushort m_vertexIndices_8;
        public ushort m_vertexIndices_9;
        public virtual uint Signature => 0x0;

        public virtual void Read(PackFileDeserializer des, BinaryReaderEx br)
        {
            m_vertexIndices_0 = br.ReadUInt16();
            m_vertexIndices_1 = br.ReadUInt16();
            m_vertexIndices_2 = br.ReadUInt16();
            m_vertexIndices_3 = br.ReadUInt16();
            m_vertexIndices_4 = br.ReadUInt16();
            m_vertexIndices_5 = br.ReadUInt16();
            m_vertexIndices_6 = br.ReadUInt16();
            m_vertexIndices_7 = br.ReadUInt16();
            m_vertexIndices_8 = br.ReadUInt16();
            m_vertexIndices_9 = br.ReadUInt16();
            m_vertexIndices_10 = br.ReadUInt16();
            m_vertexIndices_11 = br.ReadUInt16();
            m_vertexIndices_12 = br.ReadUInt16();
            m_vertexIndices_13 = br.ReadUInt16();
            m_vertexIndices_14 = br.ReadUInt16();
            m_vertexIndices_15 = br.ReadUInt16();
            m_boneIndices_0 = br.ReadUInt16();
            m_boneIndices_1 = br.ReadUInt16();
            m_boneIndices_2 = br.ReadUInt16();
            m_boneIndices_3 = br.ReadUInt16();
            m_boneIndices_4 = br.ReadUInt16();
            m_boneIndices_5 = br.ReadUInt16();
            m_boneIndices_6 = br.ReadUInt16();
            m_boneIndices_7 = br.ReadUInt16();
            m_boneIndices_8 = br.ReadUInt16();
            m_boneIndices_9 = br.ReadUInt16();
            m_boneIndices_10 = br.ReadUInt16();
            m_boneIndices_11 = br.ReadUInt16();
            m_boneIndices_12 = br.ReadUInt16();
            m_boneIndices_13 = br.ReadUInt16();
            m_boneIndices_14 = br.ReadUInt16();
            m_boneIndices_15 = br.ReadUInt16();
            m_boneIndices_16 = br.ReadUInt16();
            m_boneIndices_17 = br.ReadUInt16();
            m_boneIndices_18 = br.ReadUInt16();
            m_boneIndices_19 = br.ReadUInt16();
            m_boneIndices_20 = br.ReadUInt16();
            m_boneIndices_21 = br.ReadUInt16();
            m_boneIndices_22 = br.ReadUInt16();
            m_boneIndices_23 = br.ReadUInt16();
            m_boneIndices_24 = br.ReadUInt16();
            m_boneIndices_25 = br.ReadUInt16();
            m_boneIndices_26 = br.ReadUInt16();
            m_boneIndices_27 = br.ReadUInt16();
            m_boneIndices_28 = br.ReadUInt16();
            m_boneIndices_29 = br.ReadUInt16();
            m_boneIndices_30 = br.ReadUInt16();
            m_boneIndices_31 = br.ReadUInt16();
            m_boneIndices_32 = br.ReadUInt16();
            m_boneIndices_33 = br.ReadUInt16();
            m_boneIndices_34 = br.ReadUInt16();
            m_boneIndices_35 = br.ReadUInt16();
            m_boneIndices_36 = br.ReadUInt16();
            m_boneIndices_37 = br.ReadUInt16();
            m_boneIndices_38 = br.ReadUInt16();
            m_boneIndices_39 = br.ReadUInt16();
            m_boneIndices_40 = br.ReadUInt16();
            m_boneIndices_41 = br.ReadUInt16();
            m_boneIndices_42 = br.ReadUInt16();
            m_boneIndices_43 = br.ReadUInt16();
            m_boneIndices_44 = br.ReadUInt16();
            m_boneIndices_45 = br.ReadUInt16();
            m_boneIndices_46 = br.ReadUInt16();
            m_boneIndices_47 = br.ReadUInt16();
            m_boneIndices_48 = br.ReadUInt16();
            m_boneIndices_49 = br.ReadUInt16();
            m_boneIndices_50 = br.ReadUInt16();
            m_boneIndices_51 = br.ReadUInt16();
            m_boneIndices_52 = br.ReadUInt16();
            m_boneIndices_53 = br.ReadUInt16();
            m_boneIndices_54 = br.ReadUInt16();
            m_boneIndices_55 = br.ReadUInt16();
            m_boneIndices_56 = br.ReadUInt16();
            m_boneIndices_57 = br.ReadUInt16();
            m_boneIndices_58 = br.ReadUInt16();
            m_boneIndices_59 = br.ReadUInt16();
            m_boneIndices_60 = br.ReadUInt16();
            m_boneIndices_61 = br.ReadUInt16();
            m_boneIndices_62 = br.ReadUInt16();
            m_boneIndices_63 = br.ReadUInt16();
            m_boneIndices_64 = br.ReadUInt16();
            m_boneIndices_65 = br.ReadUInt16();
            m_boneIndices_66 = br.ReadUInt16();
            m_boneIndices_67 = br.ReadUInt16();
            m_boneIndices_68 = br.ReadUInt16();
            m_boneIndices_69 = br.ReadUInt16();
            m_boneIndices_70 = br.ReadUInt16();
            m_boneIndices_71 = br.ReadUInt16();
            m_boneIndices_72 = br.ReadUInt16();
            m_boneIndices_73 = br.ReadUInt16();
            m_boneIndices_74 = br.ReadUInt16();
            m_boneIndices_75 = br.ReadUInt16();
            m_boneIndices_76 = br.ReadUInt16();
            m_boneIndices_77 = br.ReadUInt16();
            m_boneIndices_78 = br.ReadUInt16();
            m_boneIndices_79 = br.ReadUInt16();
            m_boneIndices_80 = br.ReadUInt16();
            m_boneIndices_81 = br.ReadUInt16();
            m_boneIndices_82 = br.ReadUInt16();
            m_boneIndices_83 = br.ReadUInt16();
            m_boneIndices_84 = br.ReadUInt16();
            m_boneIndices_85 = br.ReadUInt16();
            m_boneIndices_86 = br.ReadUInt16();
            m_boneIndices_87 = br.ReadUInt16();
            m_boneIndices_88 = br.ReadUInt16();
            m_boneIndices_89 = br.ReadUInt16();
            m_boneIndices_90 = br.ReadUInt16();
            m_boneIndices_91 = br.ReadUInt16();
            m_boneIndices_92 = br.ReadUInt16();
            m_boneIndices_93 = br.ReadUInt16();
            m_boneIndices_94 = br.ReadUInt16();
            m_boneIndices_95 = br.ReadUInt16();
            m_boneWeights_0 = br.ReadUInt16();
            m_boneWeights_1 = br.ReadUInt16();
            m_boneWeights_2 = br.ReadUInt16();
            m_boneWeights_3 = br.ReadUInt16();
            m_boneWeights_4 = br.ReadUInt16();
            m_boneWeights_5 = br.ReadUInt16();
            m_boneWeights_6 = br.ReadUInt16();
            m_boneWeights_7 = br.ReadUInt16();
            m_boneWeights_8 = br.ReadUInt16();
            m_boneWeights_9 = br.ReadUInt16();
            m_boneWeights_10 = br.ReadUInt16();
            m_boneWeights_11 = br.ReadUInt16();
            m_boneWeights_12 = br.ReadUInt16();
            m_boneWeights_13 = br.ReadUInt16();
            m_boneWeights_14 = br.ReadUInt16();
            m_boneWeights_15 = br.ReadUInt16();
            m_boneWeights_16 = br.ReadUInt16();
            m_boneWeights_17 = br.ReadUInt16();
            m_boneWeights_18 = br.ReadUInt16();
            m_boneWeights_19 = br.ReadUInt16();
            m_boneWeights_20 = br.ReadUInt16();
            m_boneWeights_21 = br.ReadUInt16();
            m_boneWeights_22 = br.ReadUInt16();
            m_boneWeights_23 = br.ReadUInt16();
            m_boneWeights_24 = br.ReadUInt16();
            m_boneWeights_25 = br.ReadUInt16();
            m_boneWeights_26 = br.ReadUInt16();
            m_boneWeights_27 = br.ReadUInt16();
            m_boneWeights_28 = br.ReadUInt16();
            m_boneWeights_29 = br.ReadUInt16();
            m_boneWeights_30 = br.ReadUInt16();
            m_boneWeights_31 = br.ReadUInt16();
            m_boneWeights_32 = br.ReadUInt16();
            m_boneWeights_33 = br.ReadUInt16();
            m_boneWeights_34 = br.ReadUInt16();
            m_boneWeights_35 = br.ReadUInt16();
            m_boneWeights_36 = br.ReadUInt16();
            m_boneWeights_37 = br.ReadUInt16();
            m_boneWeights_38 = br.ReadUInt16();
            m_boneWeights_39 = br.ReadUInt16();
            m_boneWeights_40 = br.ReadUInt16();
            m_boneWeights_41 = br.ReadUInt16();
            m_boneWeights_42 = br.ReadUInt16();
            m_boneWeights_43 = br.ReadUInt16();
            m_boneWeights_44 = br.ReadUInt16();
            m_boneWeights_45 = br.ReadUInt16();
            m_boneWeights_46 = br.ReadUInt16();
            m_boneWeights_47 = br.ReadUInt16();
            m_boneWeights_48 = br.ReadUInt16();
            m_boneWeights_49 = br.ReadUInt16();
            m_boneWeights_50 = br.ReadUInt16();
            m_boneWeights_51 = br.ReadUInt16();
            m_boneWeights_52 = br.ReadUInt16();
            m_boneWeights_53 = br.ReadUInt16();
            m_boneWeights_54 = br.ReadUInt16();
            m_boneWeights_55 = br.ReadUInt16();
            m_boneWeights_56 = br.ReadUInt16();
            m_boneWeights_57 = br.ReadUInt16();
            m_boneWeights_58 = br.ReadUInt16();
            m_boneWeights_59 = br.ReadUInt16();
            m_boneWeights_60 = br.ReadUInt16();
            m_boneWeights_61 = br.ReadUInt16();
            m_boneWeights_62 = br.ReadUInt16();
            m_boneWeights_63 = br.ReadUInt16();
            m_boneWeights_64 = br.ReadUInt16();
            m_boneWeights_65 = br.ReadUInt16();
            m_boneWeights_66 = br.ReadUInt16();
            m_boneWeights_67 = br.ReadUInt16();
            m_boneWeights_68 = br.ReadUInt16();
            m_boneWeights_69 = br.ReadUInt16();
            m_boneWeights_70 = br.ReadUInt16();
            m_boneWeights_71 = br.ReadUInt16();
            m_boneWeights_72 = br.ReadUInt16();
            m_boneWeights_73 = br.ReadUInt16();
            m_boneWeights_74 = br.ReadUInt16();
            m_boneWeights_75 = br.ReadUInt16();
            m_boneWeights_76 = br.ReadUInt16();
            m_boneWeights_77 = br.ReadUInt16();
            m_boneWeights_78 = br.ReadUInt16();
            m_boneWeights_79 = br.ReadUInt16();
            m_boneWeights_80 = br.ReadUInt16();
            m_boneWeights_81 = br.ReadUInt16();
            m_boneWeights_82 = br.ReadUInt16();
            m_boneWeights_83 = br.ReadUInt16();
            m_boneWeights_84 = br.ReadUInt16();
            m_boneWeights_85 = br.ReadUInt16();
            m_boneWeights_86 = br.ReadUInt16();
            m_boneWeights_87 = br.ReadUInt16();
            m_boneWeights_88 = br.ReadUInt16();
            m_boneWeights_89 = br.ReadUInt16();
            m_boneWeights_90 = br.ReadUInt16();
            m_boneWeights_91 = br.ReadUInt16();
            m_boneWeights_92 = br.ReadUInt16();
            m_boneWeights_93 = br.ReadUInt16();
            m_boneWeights_94 = br.ReadUInt16();
            m_boneWeights_95 = br.ReadUInt16();
        }

        public virtual void Write(PackFileSerializer s, BinaryWriterEx bw)
        {
            bw.WriteUInt16(m_vertexIndices_0);
            bw.WriteUInt16(m_vertexIndices_1);
            bw.WriteUInt16(m_vertexIndices_2);
            bw.WriteUInt16(m_vertexIndices_3);
            bw.WriteUInt16(m_vertexIndices_4);
            bw.WriteUInt16(m_vertexIndices_5);
            bw.WriteUInt16(m_vertexIndices_6);
            bw.WriteUInt16(m_vertexIndices_7);
            bw.WriteUInt16(m_vertexIndices_8);
            bw.WriteUInt16(m_vertexIndices_9);
            bw.WriteUInt16(m_vertexIndices_10);
            bw.WriteUInt16(m_vertexIndices_11);
            bw.WriteUInt16(m_vertexIndices_12);
            bw.WriteUInt16(m_vertexIndices_13);
            bw.WriteUInt16(m_vertexIndices_14);
            bw.WriteUInt16(m_vertexIndices_15);
            bw.WriteUInt16(m_boneIndices_0);
            bw.WriteUInt16(m_boneIndices_1);
            bw.WriteUInt16(m_boneIndices_2);
            bw.WriteUInt16(m_boneIndices_3);
            bw.WriteUInt16(m_boneIndices_4);
            bw.WriteUInt16(m_boneIndices_5);
            bw.WriteUInt16(m_boneIndices_6);
            bw.WriteUInt16(m_boneIndices_7);
            bw.WriteUInt16(m_boneIndices_8);
            bw.WriteUInt16(m_boneIndices_9);
            bw.WriteUInt16(m_boneIndices_10);
            bw.WriteUInt16(m_boneIndices_11);
            bw.WriteUInt16(m_boneIndices_12);
            bw.WriteUInt16(m_boneIndices_13);
            bw.WriteUInt16(m_boneIndices_14);
            bw.WriteUInt16(m_boneIndices_15);
            bw.WriteUInt16(m_boneIndices_16);
            bw.WriteUInt16(m_boneIndices_17);
            bw.WriteUInt16(m_boneIndices_18);
            bw.WriteUInt16(m_boneIndices_19);
            bw.WriteUInt16(m_boneIndices_20);
            bw.WriteUInt16(m_boneIndices_21);
            bw.WriteUInt16(m_boneIndices_22);
            bw.WriteUInt16(m_boneIndices_23);
            bw.WriteUInt16(m_boneIndices_24);
            bw.WriteUInt16(m_boneIndices_25);
            bw.WriteUInt16(m_boneIndices_26);
            bw.WriteUInt16(m_boneIndices_27);
            bw.WriteUInt16(m_boneIndices_28);
            bw.WriteUInt16(m_boneIndices_29);
            bw.WriteUInt16(m_boneIndices_30);
            bw.WriteUInt16(m_boneIndices_31);
            bw.WriteUInt16(m_boneIndices_32);
            bw.WriteUInt16(m_boneIndices_33);
            bw.WriteUInt16(m_boneIndices_34);
            bw.WriteUInt16(m_boneIndices_35);
            bw.WriteUInt16(m_boneIndices_36);
            bw.WriteUInt16(m_boneIndices_37);
            bw.WriteUInt16(m_boneIndices_38);
            bw.WriteUInt16(m_boneIndices_39);
            bw.WriteUInt16(m_boneIndices_40);
            bw.WriteUInt16(m_boneIndices_41);
            bw.WriteUInt16(m_boneIndices_42);
            bw.WriteUInt16(m_boneIndices_43);
            bw.WriteUInt16(m_boneIndices_44);
            bw.WriteUInt16(m_boneIndices_45);
            bw.WriteUInt16(m_boneIndices_46);
            bw.WriteUInt16(m_boneIndices_47);
            bw.WriteUInt16(m_boneIndices_48);
            bw.WriteUInt16(m_boneIndices_49);
            bw.WriteUInt16(m_boneIndices_50);
            bw.WriteUInt16(m_boneIndices_51);
            bw.WriteUInt16(m_boneIndices_52);
            bw.WriteUInt16(m_boneIndices_53);
            bw.WriteUInt16(m_boneIndices_54);
            bw.WriteUInt16(m_boneIndices_55);
            bw.WriteUInt16(m_boneIndices_56);
            bw.WriteUInt16(m_boneIndices_57);
            bw.WriteUInt16(m_boneIndices_58);
            bw.WriteUInt16(m_boneIndices_59);
            bw.WriteUInt16(m_boneIndices_60);
            bw.WriteUInt16(m_boneIndices_61);
            bw.WriteUInt16(m_boneIndices_62);
            bw.WriteUInt16(m_boneIndices_63);
            bw.WriteUInt16(m_boneIndices_64);
            bw.WriteUInt16(m_boneIndices_65);
            bw.WriteUInt16(m_boneIndices_66);
            bw.WriteUInt16(m_boneIndices_67);
            bw.WriteUInt16(m_boneIndices_68);
            bw.WriteUInt16(m_boneIndices_69);
            bw.WriteUInt16(m_boneIndices_70);
            bw.WriteUInt16(m_boneIndices_71);
            bw.WriteUInt16(m_boneIndices_72);
            bw.WriteUInt16(m_boneIndices_73);
            bw.WriteUInt16(m_boneIndices_74);
            bw.WriteUInt16(m_boneIndices_75);
            bw.WriteUInt16(m_boneIndices_76);
            bw.WriteUInt16(m_boneIndices_77);
            bw.WriteUInt16(m_boneIndices_78);
            bw.WriteUInt16(m_boneIndices_79);
            bw.WriteUInt16(m_boneIndices_80);
            bw.WriteUInt16(m_boneIndices_81);
            bw.WriteUInt16(m_boneIndices_82);
            bw.WriteUInt16(m_boneIndices_83);
            bw.WriteUInt16(m_boneIndices_84);
            bw.WriteUInt16(m_boneIndices_85);
            bw.WriteUInt16(m_boneIndices_86);
            bw.WriteUInt16(m_boneIndices_87);
            bw.WriteUInt16(m_boneIndices_88);
            bw.WriteUInt16(m_boneIndices_89);
            bw.WriteUInt16(m_boneIndices_90);
            bw.WriteUInt16(m_boneIndices_91);
            bw.WriteUInt16(m_boneIndices_92);
            bw.WriteUInt16(m_boneIndices_93);
            bw.WriteUInt16(m_boneIndices_94);
            bw.WriteUInt16(m_boneIndices_95);
            bw.WriteUInt16(m_boneWeights_0);
            bw.WriteUInt16(m_boneWeights_1);
            bw.WriteUInt16(m_boneWeights_2);
            bw.WriteUInt16(m_boneWeights_3);
            bw.WriteUInt16(m_boneWeights_4);
            bw.WriteUInt16(m_boneWeights_5);
            bw.WriteUInt16(m_boneWeights_6);
            bw.WriteUInt16(m_boneWeights_7);
            bw.WriteUInt16(m_boneWeights_8);
            bw.WriteUInt16(m_boneWeights_9);
            bw.WriteUInt16(m_boneWeights_10);
            bw.WriteUInt16(m_boneWeights_11);
            bw.WriteUInt16(m_boneWeights_12);
            bw.WriteUInt16(m_boneWeights_13);
            bw.WriteUInt16(m_boneWeights_14);
            bw.WriteUInt16(m_boneWeights_15);
            bw.WriteUInt16(m_boneWeights_16);
            bw.WriteUInt16(m_boneWeights_17);
            bw.WriteUInt16(m_boneWeights_18);
            bw.WriteUInt16(m_boneWeights_19);
            bw.WriteUInt16(m_boneWeights_20);
            bw.WriteUInt16(m_boneWeights_21);
            bw.WriteUInt16(m_boneWeights_22);
            bw.WriteUInt16(m_boneWeights_23);
            bw.WriteUInt16(m_boneWeights_24);
            bw.WriteUInt16(m_boneWeights_25);
            bw.WriteUInt16(m_boneWeights_26);
            bw.WriteUInt16(m_boneWeights_27);
            bw.WriteUInt16(m_boneWeights_28);
            bw.WriteUInt16(m_boneWeights_29);
            bw.WriteUInt16(m_boneWeights_30);
            bw.WriteUInt16(m_boneWeights_31);
            bw.WriteUInt16(m_boneWeights_32);
            bw.WriteUInt16(m_boneWeights_33);
            bw.WriteUInt16(m_boneWeights_34);
            bw.WriteUInt16(m_boneWeights_35);
            bw.WriteUInt16(m_boneWeights_36);
            bw.WriteUInt16(m_boneWeights_37);
            bw.WriteUInt16(m_boneWeights_38);
            bw.WriteUInt16(m_boneWeights_39);
            bw.WriteUInt16(m_boneWeights_40);
            bw.WriteUInt16(m_boneWeights_41);
            bw.WriteUInt16(m_boneWeights_42);
            bw.WriteUInt16(m_boneWeights_43);
            bw.WriteUInt16(m_boneWeights_44);
            bw.WriteUInt16(m_boneWeights_45);
            bw.WriteUInt16(m_boneWeights_46);
            bw.WriteUInt16(m_boneWeights_47);
            bw.WriteUInt16(m_boneWeights_48);
            bw.WriteUInt16(m_boneWeights_49);
            bw.WriteUInt16(m_boneWeights_50);
            bw.WriteUInt16(m_boneWeights_51);
            bw.WriteUInt16(m_boneWeights_52);
            bw.WriteUInt16(m_boneWeights_53);
            bw.WriteUInt16(m_boneWeights_54);
            bw.WriteUInt16(m_boneWeights_55);
            bw.WriteUInt16(m_boneWeights_56);
            bw.WriteUInt16(m_boneWeights_57);
            bw.WriteUInt16(m_boneWeights_58);
            bw.WriteUInt16(m_boneWeights_59);
            bw.WriteUInt16(m_boneWeights_60);
            bw.WriteUInt16(m_boneWeights_61);
            bw.WriteUInt16(m_boneWeights_62);
            bw.WriteUInt16(m_boneWeights_63);
            bw.WriteUInt16(m_boneWeights_64);
            bw.WriteUInt16(m_boneWeights_65);
            bw.WriteUInt16(m_boneWeights_66);
            bw.WriteUInt16(m_boneWeights_67);
            bw.WriteUInt16(m_boneWeights_68);
            bw.WriteUInt16(m_boneWeights_69);
            bw.WriteUInt16(m_boneWeights_70);
            bw.WriteUInt16(m_boneWeights_71);
            bw.WriteUInt16(m_boneWeights_72);
            bw.WriteUInt16(m_boneWeights_73);
            bw.WriteUInt16(m_boneWeights_74);
            bw.WriteUInt16(m_boneWeights_75);
            bw.WriteUInt16(m_boneWeights_76);
            bw.WriteUInt16(m_boneWeights_77);
            bw.WriteUInt16(m_boneWeights_78);
            bw.WriteUInt16(m_boneWeights_79);
            bw.WriteUInt16(m_boneWeights_80);
            bw.WriteUInt16(m_boneWeights_81);
            bw.WriteUInt16(m_boneWeights_82);
            bw.WriteUInt16(m_boneWeights_83);
            bw.WriteUInt16(m_boneWeights_84);
            bw.WriteUInt16(m_boneWeights_85);
            bw.WriteUInt16(m_boneWeights_86);
            bw.WriteUInt16(m_boneWeights_87);
            bw.WriteUInt16(m_boneWeights_88);
            bw.WriteUInt16(m_boneWeights_89);
            bw.WriteUInt16(m_boneWeights_90);
            bw.WriteUInt16(m_boneWeights_91);
            bw.WriteUInt16(m_boneWeights_92);
            bw.WriteUInt16(m_boneWeights_93);
            bw.WriteUInt16(m_boneWeights_94);
            bw.WriteUInt16(m_boneWeights_95);
        }
    }
}