using System.Collections.Generic;
using System.Numerics;

namespace HKX2
{
    public enum ReintegrationRecollideMode
    {
        RR_MODE_REINTEGRATE = 1,
        RR_MODE_RECOLLIDE_BROADPHASE = 2,
        RR_MODE_RECOLLIDE_NARROWPHASE = 4,
        RR_MODE_ALL = 7
    }

    public enum MtAccessChecking
    {
        MT_ACCESS_CHECKING_ENABLED = 0,
        MT_ACCESS_CHECKING_DISABLED = 1
    }

    public enum CachedAabbUpdate
    {
        SHIFT_BROADPHASE_UPDATE_ENTITY_AABBS = 0,
        SHIFT_BROADPHASE_IGNORE_ENTITY_AABBS = 1
    }

    public class hkpWorld : hkReferencedObject
    {
        public bool m_allowIntegrationOfIslandsWithoutConstraintsInASeparateJob;
        public bool m_blockExecutingPendingOperations;
        public Vector4 m_broadPhaseExtents_0;
        public Vector4 m_broadPhaseExtents_1;
        public int m_broadPhaseNumMarkers;
        public int m_broadPhaseQuerySize;
        public int m_broadPhaseUpdateSize;
        public bool m_criticalOperationsAllowed;
        public int m_criticalOperationsLockCount;
        public int m_criticalOperationsLockCountForPhantoms;
        public float m_deactivationReferenceDistance;
        public bool m_enableToiWeldRejection;
        public hkpRigidBody m_fixedRigidBody;
        public Vector4 m_gravity;
        public int m_isLocked;
        public uint m_lastConstraintUid;
        public uint m_lastEntityUid;
        public uint m_lastIslandUid;
        public int m_maxEntriesPerToiMidphaseCollideTask;
        public int m_maxEntriesPerToiNarrowphaseCollideTask;
        public int m_maxNumToiCollisionPairsSinglethreaded;
        public int m_maxSectorsPerMidphaseCollideTask;
        public int m_maxSectorsPerNarrowphaseCollideTask;
        public uint m_minDesiredIslandSize;
        public float m_numToisTillAllowedPenetrationSimplifiedToi;
        public float m_numToisTillAllowedPenetrationToi;
        public float m_numToisTillAllowedPenetrationToiForced;
        public float m_numToisTillAllowedPenetrationToiHigher;
        public int m_pendingOperationQueueCount;
        public int m_pendingOperationsCount;
        public List<hkpPhantom> m_phantoms;
        public bool m_processActionsInSingleThread;
        public bool m_processToisMultithreaded;
        public bool m_shouldActivateOnRigidBodyTransformChange;

        public hkpSimulation m_simulation;
        public int m_sizeOfToiEventQueue;
        public float m_snapCollisionToConcaveEdgeThreshold;
        public float m_snapCollisionToConvexEdgeThreshold;
        public float m_toiCollisionResponseRotateNormal;
        public bool m_useCompoundSpuElf;
        public bool m_wantDeactivation;
        public bool m_wantSimulationIslands;
        public override uint Signature => 0;

        public override void Read(PackFileDeserializer des, BinaryReaderEx br)
        {
            base.Read(des, br);
            m_simulation = des.ReadClassPointer<hkpSimulation>(br);
            br.ReadUInt64();
            m_gravity = des.ReadVector4(br);
            br.ReadUInt64();
            m_fixedRigidBody = des.ReadClassPointer<hkpRigidBody>(br);
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            m_pendingOperationsCount = br.ReadInt32();
            br.ReadUInt32();
            m_criticalOperationsLockCount = br.ReadInt32();
            m_criticalOperationsLockCountForPhantoms = br.ReadInt32();
            m_blockExecutingPendingOperations = br.ReadBoolean();
            m_criticalOperationsAllowed = br.ReadBoolean();
            br.ReadUInt64();
            br.ReadUInt32();
            br.ReadUInt16();
            m_pendingOperationQueueCount = br.ReadInt32();
            br.ReadUInt64();
            br.ReadUInt32();
            m_processActionsInSingleThread = br.ReadBoolean();
            m_allowIntegrationOfIslandsWithoutConstraintsInASeparateJob = br.ReadBoolean();
            br.ReadUInt16();
            m_minDesiredIslandSize = br.ReadUInt32();
            br.ReadUInt64();
            m_isLocked = br.ReadInt32();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt32();
            m_wantSimulationIslands = br.ReadBoolean();
            br.ReadUInt16();
            br.ReadByte();
            m_snapCollisionToConvexEdgeThreshold = br.ReadSingle();
            m_snapCollisionToConcaveEdgeThreshold = br.ReadSingle();
            m_enableToiWeldRejection = br.ReadBoolean();
            m_wantDeactivation = br.ReadBoolean();
            m_shouldActivateOnRigidBodyTransformChange = br.ReadBoolean();
            br.ReadByte();
            m_deactivationReferenceDistance = br.ReadSingle();
            m_toiCollisionResponseRotateNormal = br.ReadSingle();
            m_maxSectorsPerMidphaseCollideTask = br.ReadInt32();
            m_maxSectorsPerNarrowphaseCollideTask = br.ReadInt32();
            m_processToisMultithreaded = br.ReadBoolean();
            br.ReadUInt16();
            br.ReadByte();
            m_maxEntriesPerToiMidphaseCollideTask = br.ReadInt32();
            m_maxEntriesPerToiNarrowphaseCollideTask = br.ReadInt32();
            m_maxNumToiCollisionPairsSinglethreaded = br.ReadInt32();
            br.ReadUInt32();
            m_numToisTillAllowedPenetrationSimplifiedToi = br.ReadSingle();
            m_numToisTillAllowedPenetrationToi = br.ReadSingle();
            m_numToisTillAllowedPenetrationToiHigher = br.ReadSingle();
            m_numToisTillAllowedPenetrationToiForced = br.ReadSingle();
            m_lastEntityUid = br.ReadUInt32();
            m_lastIslandUid = br.ReadUInt32();
            m_lastConstraintUid = br.ReadUInt32();
            m_phantoms = des.ReadClassPointerArray<hkpPhantom>(br);
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            br.ReadUInt64();
            m_broadPhaseExtents_0 = des.ReadVector4(br);
            m_broadPhaseExtents_1 = des.ReadVector4(br);
            m_broadPhaseNumMarkers = br.ReadInt32();
            m_sizeOfToiEventQueue = br.ReadInt32();
            m_broadPhaseQuerySize = br.ReadInt32();
            m_broadPhaseUpdateSize = br.ReadInt32();
            br.ReadByte();
            m_useCompoundSpuElf = br.ReadBoolean();
            br.ReadUInt64();
            br.ReadUInt32();
            br.ReadUInt16();
        }

        public override void Write(PackFileSerializer s, BinaryWriterEx bw)
        {
            base.Write(s, bw);
            s.WriteClassPointer(bw, m_simulation);
            bw.WriteUInt64(0);
            s.WriteVector4(bw, m_gravity);
            bw.WriteUInt64(0);
            s.WriteClassPointer(bw, m_fixedRigidBody);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteInt32(m_pendingOperationsCount);
            bw.WriteUInt32(0);
            bw.WriteInt32(m_criticalOperationsLockCount);
            bw.WriteInt32(m_criticalOperationsLockCountForPhantoms);
            bw.WriteBoolean(m_blockExecutingPendingOperations);
            bw.WriteBoolean(m_criticalOperationsAllowed);
            bw.WriteUInt64(0);
            bw.WriteUInt32(0);
            bw.WriteUInt16(0);
            bw.WriteInt32(m_pendingOperationQueueCount);
            bw.WriteUInt64(0);
            bw.WriteUInt32(0);
            bw.WriteBoolean(m_processActionsInSingleThread);
            bw.WriteBoolean(m_allowIntegrationOfIslandsWithoutConstraintsInASeparateJob);
            bw.WriteUInt16(0);
            bw.WriteUInt32(m_minDesiredIslandSize);
            bw.WriteUInt64(0);
            bw.WriteInt32(m_isLocked);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt32(0);
            bw.WriteBoolean(m_wantSimulationIslands);
            bw.WriteUInt16(0);
            bw.WriteByte(0);
            bw.WriteSingle(m_snapCollisionToConvexEdgeThreshold);
            bw.WriteSingle(m_snapCollisionToConcaveEdgeThreshold);
            bw.WriteBoolean(m_enableToiWeldRejection);
            bw.WriteBoolean(m_wantDeactivation);
            bw.WriteBoolean(m_shouldActivateOnRigidBodyTransformChange);
            bw.WriteByte(0);
            bw.WriteSingle(m_deactivationReferenceDistance);
            bw.WriteSingle(m_toiCollisionResponseRotateNormal);
            bw.WriteInt32(m_maxSectorsPerMidphaseCollideTask);
            bw.WriteInt32(m_maxSectorsPerNarrowphaseCollideTask);
            bw.WriteBoolean(m_processToisMultithreaded);
            bw.WriteUInt16(0);
            bw.WriteByte(0);
            bw.WriteInt32(m_maxEntriesPerToiMidphaseCollideTask);
            bw.WriteInt32(m_maxEntriesPerToiNarrowphaseCollideTask);
            bw.WriteInt32(m_maxNumToiCollisionPairsSinglethreaded);
            bw.WriteUInt32(0);
            bw.WriteSingle(m_numToisTillAllowedPenetrationSimplifiedToi);
            bw.WriteSingle(m_numToisTillAllowedPenetrationToi);
            bw.WriteSingle(m_numToisTillAllowedPenetrationToiHigher);
            bw.WriteSingle(m_numToisTillAllowedPenetrationToiForced);
            bw.WriteUInt32(m_lastEntityUid);
            bw.WriteUInt32(m_lastIslandUid);
            bw.WriteUInt32(m_lastConstraintUid);
            s.WriteClassPointerArray(bw, m_phantoms);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            bw.WriteUInt64(0);
            s.WriteVector4(bw, m_broadPhaseExtents_0);
            s.WriteVector4(bw, m_broadPhaseExtents_1);
            bw.WriteInt32(m_broadPhaseNumMarkers);
            bw.WriteInt32(m_sizeOfToiEventQueue);
            bw.WriteInt32(m_broadPhaseQuerySize);
            bw.WriteInt32(m_broadPhaseUpdateSize);
            bw.WriteByte(0);
            bw.WriteBoolean(m_useCompoundSpuElf);
            bw.WriteUInt64(0);
            bw.WriteUInt32(0);
            bw.WriteUInt16(0);
        }
    }
}